# Generated by Django 4.2.2 on 2023-06-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_features_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='feature',
            field=models.CharField(max_length=50, verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engranagem'), ('lni-laptop-phone', 'Laptop'), ('lni-leaf', 'Folha'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete')], max_length=16, verbose_name='Icone'),
        ),
    ]